# Generated by Django 3.1.2 on 2020-10-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_abtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlrequest',
            old_name='parent_mlagorithm',
            new_name='parent_mlalgorithm',
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.mlalgorithm'),
        ),
    ]
